# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.box = "mint-mate-19.0"
  config.vm.box = "my_dev_env2"
  
  config.disksize.size = '150GB'
  config.vbguest.auto_update = true
  
  config.vm.network "forwarded_port", guest: 8888, host: 8888
  
  config.vm.network :private_network, ip:"192.168.56.20"
  
  config.vm.synced_folder "./scripts", "/my_dev_settings"
  
  config.vm.provider :virtualbox do |v, override|
    v.gui = true
    v.customize ["modifyvm", :id, "--memory", 10000]
    v.customize ["modifyvm", :id, "--cpus", 4]
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.customize ["setextradata", "global", "GUI/MaxGuestResolution", "any"]
    v.customize ["setextradata", :id, "CustomVideoMode1", "1024x768x32"]
    v.customize ["modifyvm", :id, "--rtcuseutc", "on"]
    v.customize ["modifyvm", :id, "--accelerate3d", "on"]
v.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
v.customize ["modifyvm", :id, "--hwvirtex", "on"]
v.customize ["modifyvm", :id, "--nestedpaging", "on"]
v.customize ["modifyvm", :id, "--largepages", "on"]
v.customize ["modifyvm", :id, "--ioapic", "on"]
v.customize ["modifyvm", :id, "--pae", "on"]
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    
    v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
  
  config.vm.provision "kernel", type:"shell", run: "never", inline: <<-SHELL
    rm -rf /opt/my_dev_settings
    cp -rf /my_dev_settings /opt/ && chmod 777 /opt/my_dev_settings/ -R
    cd /opt/my_dev_settings
    ./base_setup.sh kernel
  SHELL
  
  config.vm.provision "my_dev_base", type:"shell", run: "never", inline: <<-SHELL
    rm -rf /opt/my_dev_settings
    cp -rf /my_dev_settings /opt/ && chmod 777 /opt/my_dev_settings/ -R
    cd /opt/my_dev_settings
    ./base_setup.sh base
  SHELL
  
  config.vm.provision "my_dev", type:"shell", run: "never", inline: <<-SHELL
    rm -rf /opt/my_dev_settings
    cp -rf /my_dev_settings /opt/ && chmod 777 /opt/my_dev_settings/ -R
    cd /opt/my_dev_settings
    ./my_dev_setup.sh
  SHELL

end
